spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.101.129:3306/gulimall_pms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  # mapper文件位置
  global-config:
    db-config:
      id-type: auto                             # 数据库主键自增
server:
  port: 10100
